# -*- coding: utf-8 -*-
"""data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MSbnI27kI4MeTlWRFjhXKjcyUEmXE1jR
"""



import pandas as pd

file_path = '/content/dataset_energie_v2.xlsx'
df = pd.read_excel(file_path)

print("Data loaded successfully. Here are the first 5 rows:")
display(df.head())

# Fill missing values in 'PUISSANCE INSTANTANNE TOTAL' based on the user's formula
df['PUISSANCE INSTANTANNE TOTAL'] = df['PUISSANCE INSTANTANNE TOTAL'].fillna(
    df['CONSOMMATION EN KWH PAR LA JIRAMA OU CONSOMMATION JOURNALIER DU CLIENT'] / 20
)

print("DataFrame info after filling missing values in 'PUISSANCE INSTANTANNE TOTAL':")
df.info()

print("\nFirst 5 rows of the DataFrame after imputation:")
display(df.head())

print("Descriptive statistics for the DataFrame:")
display(df.describe())

import matplotlib.pyplot as plt
import seaborn as sns

# Set the aesthetic style of the plots
sns.set_style("whitegrid")

# Create a figure and a set of subplots
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# Histogram for 'PUISSANCE INSTANTANNE TOTAL'
sns.histplot(df['PUISSANCE INSTANTANNE TOTAL'], kde=True, ax=axes[0])
axes[0].set_title('Distribution of PUISSANCE INSTANTANNE TOTAL')
axes[0].set_xlabel('Puissance Instantanée Totale')
axes[0].set_ylabel('Frequency')

# Histogram for 'CONSOMMATION EN KWH PAR LA JIRAMA OU CONSOMMATION JOURNALIER DU CLIENT'
sns.histplot(df['CONSOMMATION EN KWH PAR LA JIRAMA OU CONSOMMATION JOURNALIER DU CLIENT'], kde=True, ax=axes[1])
axes[1].set_title('Distribution of CONSOMMATION EN KWH PAR LA JIRAMA OU CONSOMMATION JOURNALIER DU CLIENT')
axes[1].set_xlabel('Consommation en kWh')
axes[1].set_ylabel('Frequency')

plt.tight_layout()
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

# Calculate the correlation matrix for numerical columns
correlation_matrix = df.corr(numeric_only=True)

print("Correlation Matrix:")
display(correlation_matrix)

# Plotting the heatmap
plt.figure(figsize=(10, 8))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f")
plt.title('Correlation Matrix of Numerical Variables')
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

# Create a scatter plot to visualize the relationship between the two variables
plt.figure(figsize=(10, 6))
sns.scatterplot(x='CONSOMMATION EN KWH PAR LA JIRAMA OU CONSOMMATION JOURNALIER DU CLIENT', y='PUISSANCE INSTANTANNE TOTAL', data=df)
plt.title('Scatter Plot of PUISSANCE INSTANTANNE TOTAL vs. CONSOMMATION EN KWH PAR LA JIRAMA OU CONSOMMATION JOURNALIER DU CLIENT')
plt.xlabel('CONSOMMATION EN KWH PAR LA JIRAMA OU CONSOMMATION JOURNALIER DU CLIENT')
plt.ylabel('PUISSANCE INSTANTANNE TOTAL')
plt.grid(True)
plt.show()

"""Ce nuage de points visualise la relation directe entre la 'PUISSANCE INSTANTANNE TOTAL' et la 'CONSOMMATION EN KWH PAR LA JIRAMA OU CONSOMMATION JOURNALIER DU CLIENT'.

*   Chaque point représente une observation dans votre DataFrame.
*   L'axe des x montre la 'CONSOMMATION EN KWH PAR LA JIRAMA OU CONSOMMATION JOURNALIER DU CLIENT'.
*   L'axe des y montre la 'PUISSANCE INSTANTANNE TOTAL'.

En observant la répartition des points, nous pouvons visuellement identifier s'il existe une corrélation positive (les points montent de gauche à droite), négative (les points descendent de gauche à droite), ou aucune corrélation claire.
"""

import matplotlib.pyplot as plt
import seaborn as sns

# List of numerical columns to plot (excluding 'CLIENT N' and the ones already plotted extensively)
numerical_cols = ['BATTERIE ', 'PANNEAU', 'ONDULEUR'] # Corrected column name here

# Create subplots for each numerical column
fig, axes = plt.subplots(1, len(numerical_cols), figsize=(5 * len(numerical_cols), 6))

# Ensure axes is an array even if there's only one column
if len(numerical_cols) == 1:
    axes = [axes]

for i, col in enumerate(numerical_cols):
    sns.boxplot(y=df[col], ax=axes[i])
    axes[i].set_title(f'Distribution of {col}')
    axes[i].set_ylabel(col)

plt.tight_layout()
plt.show()

"""Ces diagrammes en boîte (box plots) montrent la distribution de chaque variable :

*   La **ligne au milieu** de la boîte représente la médiane (50ème percentile).
*   Les **bords de la boîte** représentent le premier quartile (25ème percentile) et le troisième quartile (75ème percentile).
*   Les **moustaches (whiskers)** s'étendent aux valeurs minimales et maximales à l'intérieur de 1,5 fois l'intervalle interquartile (IQR).
*   Les **points individuels** au-delà des moustaches représentent les valeurs aberrantes (outliers).

Cette visualisation nous permet de rapidement identifier la plage de valeurs, la symétrie de la distribution et la présence de valeurs extrêmes pour 'BATTERIE', 'PANNEAU' et 'ONDULEUR'.
"""

print(df.columns)

import pandas as pd
from sklearn.model_selection import train_test_split

# Define feature columns (X) and target columns (y)
# Ensure column names match exactly, including any leading/trailing spaces
X_columns = [
    'CONSOMMATION EN KWH PAR LA JIRAMA OU CONSOMMATION JOURNALIER DU CLIENT',
    'PUISSANCE INSTANTANNE TOTAL'
]
y_columns = ['BATTERIE ', 'PANNEAU', 'ONDULEUR'] # Using corrected column name for BATTERIE

X = df[X_columns]
y = df[y_columns]

print("Features (X) shape:", X.shape)
print("Targets (y) shape:", y.shape)

# Split the data into training and testing sets
# We'll use 80% of the data for training and 20% for testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

print("\nFirst 5 rows of X_train:")
display(X_train.head())

print("\nFirst 5 rows of y_train:")
display(y_train.head())

from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score, mean_absolute_error

# Initialize the RandomForestRegressor model
# Using a random_state for reproducibility
model = RandomForestRegressor(n_estimators=100, random_state=42)

# Train the model on the training data
model.fit(X_train, y_train)

print("Model training complete.")

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
r2 = r2_score(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)

print(f"\nR-squared (R2) score: {r2:.4f}")
print(f"Mean Absolute Error (MAE): {mae:.4f}")

print("\nFirst 5 predictions:")
display(pd.DataFrame(y_pred, columns=y_test.columns).head())

print("\nFirst 5 actual values from test set:")
display(y_test.head())

import joblib

# Save the trained model
joblib.dump(model, 'model_solaire.pkl')

print("Model 'model_solaire.pkl' saved successfully.")

from google.colab import files

# Download the model file
files.download('model_solaire.pkl')

print("Downloading 'model_solaire.pkl'...")

```python
!pip install flask flask-cors scikit-learn joblib
# !python api_solaire.py  # Commented out to avoid running a redundant Flask server
```

!pip install flask flask-cors pyngrok -q

from flask import Flask, request, jsonify
from flask_cors import CORS
from pyngrok import ngrok
import joblib
import numpy as np
import threading

app = Flask(__name__)
CORS(app)

# Chargement de votre modèle
model = joblib.load('model_solaire.pkl')
print("✅ Modèle chargé avec succès")

@app.route('/health', methods=['GET'])
def health():
    return jsonify({"status": "ok", "message": "Modèle opérationnel"})

@app.route('/predict', methods=['POST'])
def predict():
    data = request.get_json()
    consommation_kwh = float(data['consommation_kwh'])
    puissance_kw     = float(data['puissance_kw'])

    X = np.array([[consommation_kwh, puissance_kw]])
    prediction = model.predict(X)[0]

    batterie = float(prediction[0])
    panneau  = float(prediction[1])
    onduleur = float(prediction[2])

    if puissance_kw > 5:
        conseil = f"Installation de forte puissance ({puissance_kw:.1f} kW). Prévoyez un câblage adapté."
    elif batterie > 20:
        conseil = f"Capacité batterie importante ({batterie:.1f} kWh). Optez pour des batteries lithium LiFePO4."
    elif consommation_kwh < 3:
        conseil = "Faible consommation. Un système compact suffit. Orientez les panneaux plein nord à Madagascar."
    else:
        conseil = f"Installation standard. Panneau {panneau:.0f} Wc + batterie {batterie:.1f} kWh + onduleur {onduleur:.1f} kW."

    return jsonify({
        "batterie_kwh": round(batterie, 2),
        "panneau_wc":   round(panneau, 0),
        "onduleur_kw":  round(onduleur, 2),
        "conseil": conseil
    })

# Lancement dans un thread séparé
threading.Thread(target=lambda: app.run(port=5000)).start()

# Création du tunnel public avec ngrok
url_publique = ngrok.connect(5000)
print(f"\n🌐 URL publique de votre API : {url_publique}")
print("👆 Copiez cette URL dans le champ 'URL du serveur' du fichier HTML")

import requests
r = requests.get(f"{url_publique}/health")
print(r.json())
```

---

**Ensuite dans votre fichier HTML**, remplacez `http://localhost:5000` par l'URL ngrok qui ressemble à :
```
https://xxxx-xx-xx-xxx-xx.ngrok-free.app

"""The model has been trained and evaluated. Here's what the metrics mean:

*   **R-squared (R2) score:** This metric represents the proportion of the variance in the dependent variable that is predictable from the independent variables. A higher R2 score (closer to 1.0) indicates a better fit.
*   **Mean Absolute Error (MAE):** This is the average of the absolute differences between predictions and actual observations. A lower MAE indicates better model accuracy, as it measures the average magnitude of the errors in a set of predictions, without considering their direction.

Since we have a multi-output regression, these scores are aggregated across all target variables. The initial predictions and actual values from the test set are also displayed for a quick visual comparison.

Now that we have prepared our data by splitting it into training and testing sets, the next step is to choose and train a machine learning model. For a multi-output regression task, a simple yet effective model to start with is a `RandomForestRegressor`.

After training, we will evaluate its performance using appropriate metrics like R-squared and Mean Absolute Error.
"""